TheKingOfCss3 = document.querySelector('.TheKingOfCss3');
$_$$__$ = document.querySelectorAll('.TheKingOfCss3 .--__- .-_-_-');
__$_$__$__$ = JSON.parse(localStorage.getItem('$$')) || ['YoutTube', 'Facebook', 'Mario', 'Battle Game', 'Mario Run', 'CSS King', 'Maps', 'Flappy Bird'];
_$$_$___$ = JSON.parse(localStorage.getItem('$$__')) || ['https://youtube.com','https://facebook.com','https://game10.elbakyan.am','https://game12.elbakyan.am','https://game9.elbakyan.am','../cssKing.html','https://www.google.com/maps','https://game1.elbakyan.am'];
_$_$$__$__$_ = JSON.parse(localStorage.getItem('_$__')) || ['img/1.png','img/2.webp','img/3.png','img/4.png','img/5.png','../king.png','img/7.png','img/8.png'];
__$$$__$f = JSON.parse(localStorage.getItem('__')) || ['.1','.1','.1','.1','1.1','1.1','1.1','1.1'];
$$$$$ = document.querySelectorAll('.TheKingOfCss3 .---_');
let ____$_;
let _$_$_;
let $_$_$;
let $$__$_$_;
__________ = new Number(1);
$$$$$.forEach((__$, $__) => (__$.onmouseenter = _ => ($$__$_$_ = $__, __________++ , __$.style.zIndex = __________), __$.onmousedown = __ => (____$_ = !0, _$_$_ = __.offsetX, $_$_$ = __.offsetY)));
$$$__$_j_ = JSON.parse(localStorage.getItem('___')) || ['.1','1.1','2.1','3.1','.1','1.1','2.1','3.1'];
__$_$__$__$.forEach((_, __$_d) => ($_$$__$[__$_d].lastElementChild.innerText = _, $_$$__$[__$_d].href = _$$_$___$[__$_d], $_$$__$[__$_d].lastElementChild.previousElementSibling.src = _$_$$__$__$_[__$_d]));
TheKingOfCss3.onmouseup = _ => ____$_ = false;
TheKingOfCss3.onmouseleave = _ => ____$_ = false;
TheKingOfCss3.onmousemove = __ => ____$_?($$$$$[$$__$_$_].style.left = __.x - _$_$_ + 'px',$$$$$[$$__$_$_].style.top = __.y - $_$_$ + 'px') : '';
_z_$ = 0;
$b_$ = !0;
__r$_ = !false;
$_$$__$.forEach((_$__$, $__e_$) => (_$__$.style.setProperty('--t', __$$$__$f[$__e_$]), _$__$.style.setProperty('--l', $$$__$_j_[$__e_$]), _$__$.ondragstart = e => { _$__$.style.background = '#E8E8E8'; _z_$ = $__e_$,e.dataTransfer.setDragImage(new Image(), 0, 0); __r$_ = false; }, _$__$.onmouseover = () => __r$_ ? _$__$.style.background = '#E8E8E8' : '', _$__$.onmouseleave = () => __r$_ ? _$__$.style.background = 'none' : '', _$__$.ondragover = () => $b_$ ? ($b_$ = false, _$_$$_$$ = __$$$__$f[$__e_$], ___$$_$__$$ = $$$__$_j_[$__e_$], __$$$__$f[$__e_$] = __$$$__$f[_z_$], $$$__$_j_[$__e_$] = $$$__$_j_[_z_$], __$$$__$f[_z_$] = _$_$$_$$, $$$__$_j_[_z_$] = ___$$_$__$$, localStorage.setItem('__', JSON.stringify(__$$$__$f)), localStorage.setItem('___', JSON.stringify($$$__$_j_)), $_$$__$.forEach((_$__$, ___) => (_$__$.style.setProperty('--t', __$$$__$f[___]), _$__$.style.setProperty('--l', $$$__$_j_[___]))), setTimeout(() => $b_$ = true, 200)) : '', _$__$.parentElement.ondragover = _ => _.preventDefault()));
TheKingOfCss3.ondrop = _ => __r$_ = true;
document.body.children[0].lastElementChild.onmouseleave = _ => $_$$__$.forEach(_$__ => _$__.style.background = 'none');
______ = 0;
(function _$() {
	const $___ = document.querySelector('.TheKingOfCss3 ._- ._');
	const $__ = ['Введите поисковый запрос или URL', 'This is MasterClass', 'Elbakyan Krtahamalir', 'Senior Developer Hovo Vardanyan'];
	let $$ = 0;
	let _ = setInterval(() => ($___.placeholder = $__[______].slice(0, $$),$$++,$___.placeholder == $__[______] ? (clearInterval(_), setTimeout(() => ( _ = setInterval(() => ($___.placeholder = $__[______].slice(0, $$), $$--, $___.placeholder == '' ? (clearInterval(_), _$(), ______++, ______ == $__.length ? ______ = 0 : '') : ''), 3e1)), 7e2)) : ''), 7e1);
})();
$$__$_$_$ = document.querySelector('._-__--__');
___$_$_ = document.querySelector('._-__--__ .__---___-');
__$__$_ = document.querySelectorAll('._-__--__ .__---___- .---_---__ input');
$x_$ = document.querySelector('._-__--__ .__---___- .__n-__- :first-child');
_$i_$ = document.querySelector('._-__--__ .__---___- .__n-__- :last-child');
_$$$_n$_ = document.querySelectorAll('.TheKingOfCss3 .--__- .-_-_- :where(.----__, .--__--__--)');
$$$$_$ = document.querySelector('._-__--__ .__---___- .---_---__ label input');
_$_ = document.querySelector('._-_');
$x_$.onclick = _ => (_$_.style.display = 'none', $$__$_$_$.style.display = 'none', _$$$_n$_.forEach(___$ => ___$.className == '--__--__--' ? ___$.style.display = 'none' : ''));
let $$i__$;
_$$$_n$_.forEach(__$_j$ => __$_j$.onclick = e => (e.preventDefault(), __$_j$.className == '----__' ? (__$_j$.previousElementSibling.style.display = 'block', _$_.style.display = 'block') : '', __$_j$.className == '--__--__--' ? ($$__$_$_$.style.display = 'grid', __$__$_[0].focus()) : ''));
_$_.onclick = e => (e.srcElement.style.display = 'none', _$$$_n$_.forEach(_ => _.className == '--__--__--' ? _.style.display = 'none' : ''));
__c$__ = document.querySelectorAll('.TheKingOfCss3 .--__- .-_-_- .----__');
__c$__.forEach(($H_, H_$) => $H_.addEventListener('click', () => ($$i__$ = H_$, __$__$_[0].value = $_$$__$[$$i__$].lastElementChild.innerText, __$__$_[1].value = $_$$__$[$$i__$]['href'])));
$$__$_$_$.onclick = _ => (___$_$_.style.animation = 'linkA .15s', ___$_$_.onanimationend = _ => ___$_$_.style.animation = 'none');
___$_$_.onclick = e => e.stopPropagation();
$$_$__$_$__$ = new FileReader();
$$$$_$.onchange = () => ($$_$__$_$__$.readAsDataURL($$$$_$.files[0]), $$_$__$_$__$.onload = () => ($_$$__$[$$i__$].lastElementChild.previousElementSibling.src = $$_$__$_$__$.result, _$_$$__$__$_[$$i__$] = $$_$__$_$__$.result));
_$i_$.onclick = () => {
	$_$$__$[$$i__$].lastElementChild.innerText = __$__$_[0].value;
	$_$$__$[$$i__$].href = __$__$_[1].value;
	__$_$__$__$[$$i__$] = __$__$_[0].value;
	_$$_$___$[$$i__$] = __$__$_[1].value;
	localStorage.setItem('$$', JSON.stringify(__$_$__$__$));
	localStorage.setItem('$$__', JSON.stringify(_$$_$___$));
	localStorage.setItem('_$__', JSON.stringify(_$_$$__$__$_));
	_$_.style.display = 'none';
	$$__$_$_$.style.display = 'none';
	_$$$_n$_.forEach(__ => __.className == '--__--__--' ? __.style.display = 'none' : '');
};
_$$__$__$_$$ = ['Google', 'The King Of CSS3', 'Perfect JavaScript Writer'];
____$_$_$ = 0;
setInterval(_ => (____$_$_$++, ____$_$_$ == _$$__$__$_$$.length ? ____$_$_$ = 0 : '', document.head.children[1].innerText = _$$__$__$_$$[____$_$_$]), 2e3);
$___$__ = document.querySelector('.TheKingOfCss3 ._- ._');
$_$_$_$ = document.querySelector('._----__-');
_$_$_$_ = document.querySelector('._----__- .--_--_');
___$__$$_ = document.querySelectorAll('._----__- .___-__-- .__-_--_');
__$_$____$ = document.querySelector('.TheKingOfCss3 ._- .___---__-_-');
$$$$$__ = document.querySelector('._----__- .--_--_ ._____--');
let _____$;
let $_____;
let __$$_$___$;
__$_$____$.onclick = _ => $_$_$_$.style.display = $_$_$_$.style.display != 'block' ? 'block' : 'none';
$$$$$__.onclick = _ => $_$_$_$.style.display = 'none';
$$$$$__.onmousedown = _ => _.stopPropagation();
_$_$_$_.onmousedown = _$ => (__$$_$___$ = true, _____$ = _$.offsetX + 13, $_____ = _$.offsetY + 13);
document.onmouseleave = _ => __$$_$___$ = false;
$_$_$_$.onmouseup = _ => __$$_$___$ = false;
document.onmousemove = $_ => __$$_$___$ ? ($_$_$_$.style.top = $_.y - $_____ + 'px', $_$_$_$.style.left = $_.x - _____$ + 'px', $_$_$_$.offsetTop < 0 ? $_$_$_$.style.top = 0 : '', $_$_$_$.offsetTop > window.innerHeight - $_$_$_$.offsetHeight ? $_$_$_$.style.top = window.innerHeight - $_$_$_$.offsetHeight + 'px' : '', $_$_$_$.offsetLeft < 0 ? $_$_$_$.style.left = 0 : '', $_$_$_$.offsetLeft > window.innerWidth - $_$_$_$.offsetWidth ? $_$_$_$.style.left = window.innerWidth - $_$_$_$.offsetWidth + 'px' : '') : '';		
$$_$_f_$ = document.querySelector('.TheKingOfCss3 ._- svg');
$$_$_f_$.onclick = _ => ($$_$_f_$.style.transform = 'rotate(360deg) scale(.85)', $$_$_f_$.ontransitionend = _ => window.location.href = `https://www.google.com/search?q=${$___$__.value}`);
$$$$$$__ = [];
$$$___ = 0;
___$$$ = 0;
$$__$$__ = true;
$___$__.onclick = _ => ($$$___ = $___$__.value.slice(0, $___$__.selectionStart).length, ___$$$ = $___$__.value.slice($___$__.selectionStart, $___$__.selectionEnd).length);
document.onmouseup = _ => ($$$___ = $___$__.value.slice(0, $___$__.selectionStart).length, ___$$$ = $___$__.value.slice($___$__.selectionStart, $___$__.selectionEnd).length);
console.log('%cDeveloper Hovo Vardanyan 2022', 'font: bold 25px/2 cursive; text-shadow: -1px 2px 1px #00ff6c, -2px 4px 3px #000; padding: 0 10px;');
___$__$$_.forEach($$__$$ => $$__$$.onclick = _ => $$__$$.classList.contains('l') ? ($$$$$$__.splice($$$___, 0, $$__$$.innerText), $$$___++, $___$__.value = $$$$$$__.join(''), ___$__$$_.forEach(_$ => _$.classList.contains('l') && $$__$$__ ? _$.innerText = _$.innerText.toLowerCase() : '')) : $$__$$.classList.contains('b') ? (___$$$ == 0 ? ($$$___ > 0 ? $$$___-- : '', $$$$$$__.splice($$$___, 1), $___$__.value = $$$$$$__.join('')) : ($$$$$$__.splice($$$___, ___$$$), $___$__.value = $$$$$$__.join('')), $___$__.focus()) : $$__$$.classList.contains('s') ? ($$$$$$__.splice($$$___, 1, ' '), $$$___++, $___$__.value = $$$$$$__.join('')) : $$__$$.classList.contains('e') ? ($$_$_f_$.style.transform = 'rotate(360deg) scale(.85)', $$_$_f_$.ontransitionend = () => window.location.href = `https://www.google.com/search?q=${$___$__.value}`) : $$__$$.classList.contains('c') ? ($$__$$__ = !$$__$$__, $$__$$.style.background != 'grey' ? ($$__$$.style.background = 'grey', $$__$$.style.color = '#fff') : ($$__$$.style.background = '#F4F4F4', $$__$$.style.color = 'rgba(0,0,0,.83)'), ___$__$$_.forEach(___ => ___.classList.contains('l') ? (___.innerText != ___.innerText.toUpperCase() ? ___.innerText = ___.innerText.toUpperCase() : ___.innerText = ___.innerText.toLowerCase()) : '')) : $$__$$.classList.contains('m') ? ___$__$$_.forEach(_$ => _$.classList.contains('l') ? _$.innerText = _$.innerText.toUpperCase() : '') : '');
$___$__.onkeydown = _$_$_$_$_$_ => _$_$_$_$_$_.which == '8' ? (___$$$ == 0 ? ($$$___ > 0 ? $$$___-- : '', $$$$$$__.splice($$$___, 1), $___$__.value = $$$$$$__.join('')) : ($$$$$$__.splice($$$___, ___$$$), $___$__.value = $$$$$$__.join('')), $___$__.value = $$$$$$__.join(''), setTimeout(_ => (___$$$ = 0, $$$___ = $___$__.value.length), 50), _$_$_$_$_$_.preventDefault()) : _$_$_$_$_$_.which == 13 ? ($$_$_f_$.style.transform = 'rotate(360deg) scale(.85)', $$_$_f_$.ontransitionend = _ => window.location.href = `https://www.google.com/search?q=${$___$__.value}`) : _$_$_$_$_$_.which == 37 ? $$$___-- : _$_$_$_$_$_.which == 39 ? $$$___++ : '';
$___$__.oninput = e => ($$$$$$__.splice($$$___, ___$$$, e.data), $$$___++);